// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Swift Student Challenge 24",
    platforms: [
        .iOS("17.2")
    ],
    products: [
        .iOSApplication(
            name: "Swift Student Challenge 24",
            targets: ["AppModule"],
            bundleIdentifier: "wwdcssc.com",
            teamIdentifier: "X622SX6D57",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.yellow),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .fileAccess(.pictureFolder, mode: .readWrite),
                .photoLibrary(purposeString: "\"Enable Saving Drawings to Photo Library\" "),
                .photoLibraryAdd(purposeString: "\"Enable Saving Drawings to Photo Library\" "),
                .microphone(purposeString: "\"Enable Speech Recognition\" "),
                .speechRecognition(purposeString: "\"Enable Speech Recognition\"")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
